############################################################
# Dockerfile to build mongo (https://hub.docker.com/_/mongo/)
############################################################
FROM mongo

# File Author / Maintainer
MAINTAINER Jordi Targa <jtarga@wearejust.digital>

################## BEGIN INSTALLATION ######################
EXPOSE 27017
